CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-- Create Table
CREATE TABLE IF NOT EXISTS urls (
    url_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid UUID NOT NULL,
    random_key VARCHAR(5) NOT NULL UNIQUE,
    default_fallback_url TEXT NOT NULL,
    hashed_value_url VARCHAR(150) UNIQUE,
    ios_deep_link TEXT,
    ios_fallback_url TEXT,
    android_deep_link TEXT,
    android_fallback_url TEXT,
    webhook_url TEXT,
    opengraph_title VARCHAR(255),
    opengraph_description TEXT,
    opengraph_image TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    url_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    url_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    url_deleted_at TIMESTAMPTZ DEFAULT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_uuid) REFERENCES users(user_uuid)
);
-- Create Comment
COMMENT ON COLUMN urls.random_key IS 'Random Key: This column contain the key to make URL shortner complex than';

-- Create Index
CREATE INDEX IF NOT EXISTS idx_urls_random_key ON urls(random_key);
CREATE INDEX IF NOT EXISTS idx_urls_user_uuid ON urls(user_uuid);
CREATE INDEX IF NOT EXISTS idx_urls_created_at ON urls(url_created_at);
CREATE INDEX IF NOT EXISTS idx_urls_deleted_at ON urls(url_deleted_at);
-- Trigger update updated_at
CREATE OR REPLACE FUNCTION update_url_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.url_updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_url_update_at
BEFORE UPDATE ON urls
FOR EACH ROW
EXECUTE FUNCTION update_url_updated_at();
