CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-- Create FUNCTION to random key
CREATE OR REPLACE FUNCTION random_string(length INTEGER) RETURNS TEXT AS $$
DECLARE
  chars TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  result TEXT := '';
BEGIN
  IF length < 1 THEN
    RAISE EXCEPTION 'The string must be longer than 4 characters';
  END IF;
  FOR i IN 1..length LOOP
    result := result || substr(chars, ceil(random() * length(chars))::integer, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;
-- Create Table
CREATE TABLE IF NOT EXISTS urls(
    url_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    random_key VARCHAR(5) NOT NULL DEFAULT random_string(5) UNIQUE,
    default_fallback_url TEXT NOT NULL,
    hashed_value_url VARCHAR(150) UNIQUE,
    ios_deep_link TEXT,
    ios_fallback_url TEXT,
    android_deep_link TEXT,
    android_fallback_url TEXT,
    webhook_url TEXT,
    opengraph_title VARCHAR(255),
    opengraph_description TEXT,
    opengraph_image TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    url_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    url_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
-- Create Comment
COMMENT ON COLUMN urls.random_key IS 'Random Key: This column contain the key to make URL shortner complex than';
-- Create Index
CREATE INDEX IF NOT EXISTS idx_urls_random_key ON urls(random_key);
CREATE INDEX IF NOT EXISTS idx_urls_user_id ON urls(user_id);
CREATE INDEX IF NOT EXISTS idx_urls_created_at ON urls(url_created_at);
-- Trigger update time
CREATE OR REPLACE FUNCTION update_url_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.url_updated_at = now();
    return NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_url_update_at
BEFORE UPDATE ON urls
FOR EACH ROW
EXECUTE FUNCTION update_url_updated_at();
