CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create Table
CREATE TABLE IF NOT EXISTS users(
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    user_email VARCHAR(150) NOT NULL UNIQUE,
    user_password VARCHAR(90) NOT NULL,
    user_role INT NOT NULL DEFAULT 1 CHECK (user_role IN (1,2,3)),
    user_status INT NOT NULL DEFAULT 1 CHECK (user_status IN (1,2,3)),
    user_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_deleted_at TIMESTAMPTZ DEFAULT NULL
);
-- Create Comment
COMMENT ON COLUMN users.user_role IS 'User Role: 1 - User, 2 - Moderator, 3 - Adminstator';
COMMENT ON COLUMN users.user_status IS 'User Status: 1 - Active, 2 - Inactive, 3 - Banned';
COMMENT ON COLUMN users.user_deleted_at IS 'Soft delete timestamp: NULL means not deleted';
-- Create Index
CREATE INDEX IF NOT EXISTS idx_user_status ON users(user_status);
CREATE INDEX IF NOT EXISTS idx_user_role ON users(user_role);
CREATE INDEX IF NOT EXISTS idx_user_created_at ON users(user_created_at);
CREATE INDEX IF NOT EXISTS idx_user_deleted_at ON users(user_deleted_at);
-- Create trigger
CREATE OR REPLACE FUNCTION update_user_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.user_updated_at = now();
    return NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_user_update_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_user_updated_at();
