#Maximum data on RAM
maxmemory 256mb

# Least recently used: When the memory has reached 256mb, Redis will remove the key has TTL (Time To Live)
maxmemory-policy volatile-lru

# Turn on persistence (RDB) to save data to database
# Save data after 900 seconds if it only has 1 modify
# Save data after 300 seconds if it only has 10 modify
# Save data after 60 seconds if it only has 10000 modify
save 900 1
save 300 10
save 60 10000
#Config the place where to save data
dir /data
