// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	UrlID    int32     `json:"url_id"`
	UserUuid uuid.UUID `json:"user_uuid"`
	// Random Key: This column contain the key to make URL shortner complex than
	RandomKey            string             `json:"random_key"`
	DefaultFallbackUrl   string             `json:"default_fallback_url"`
	HashedValueUrl       *string            `json:"hashed_value_url"`
	IosDeepLink          string             `json:"ios_deep_link"`
	IosFallbackUrl       string             `json:"ios_fallback_url"`
	AndroidDeepLink      string             `json:"android_deep_link"`
	AndroidFallbackUrl   string             `json:"android_fallback_url"`
	WebhookUrl           string             `json:"webhook_url"`
	OpengraphTitle       *string            `json:"opengraph_title"`
	OpengraphDescription string             `json:"opengraph_description"`
	OpengraphImage       string             `json:"opengraph_image"`
	IsActive             bool               `json:"is_active"`
	UrlCreatedAt         time.Time          `json:"url_created_at"`
	UrlUpdatedAt         time.Time          `json:"url_updated_at"`
	UrlDeletedAt         pgtype.Timestamptz `json:"url_deleted_at"`
}

type User struct {
	UserID       int32     `json:"user_id"`
	UserUuid     uuid.UUID `json:"user_uuid"`
	UserEmail    string    `json:"user_email"`
	UserPassword string    `json:"user_password"`
	// User Role: 1 - User, 2 - Moderator, 3 - Adminstator
	UserRole int32 `json:"user_role"`
	// User Status: 1 - Active, 2 - Inactive, 3 - Banned
	UserStatus    int32     `json:"user_status"`
	UserCreatedAt time.Time `json:"user_created_at"`
	UserUpdatedAt time.Time `json:"user_updated_at"`
	// Soft delete timestamp: NULL means not deleted
	UserDeletedAt pgtype.Timestamptz `json:"user_deleted_at"`
}
