// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CleanSoftDelete(ctx context.Context, userUuid uuid.UUID) (User, error)
	CountRecords(ctx context.Context, arg CountRecordsParams) (int64, error)
	CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindUrlByHashed(ctx context.Context, hashedValueUrl string) (Url, error)
	GetUserByEmail(ctx context.Context, userEmail string) (User, error)
	GetUserByUUID(ctx context.Context, userUuid uuid.UUID) (User, error)
	RestoreUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	SoftDeleteUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
