// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls(
    user_uuid,random_key, ios_deep_link, ios_fallback_url,
    android_deep_link, android_fallback_url, default_fallback_url,
    hashed_value_url, webhook_url, opengraph_title, opengraph_description,
    opengraph_image, is_active, url_created_at, url_updated_at
)
VALUES($13,$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), NOW())
ON CONFLICT (hashed_value_url) WHERE url_deleted_at IS NULL
DO NOTHING
RETURNING url_id, user_uuid, random_key, default_fallback_url, hashed_value_url, ios_deep_link, ios_fallback_url, android_deep_link, android_fallback_url, webhook_url, opengraph_title, opengraph_description, opengraph_image, is_active, url_created_at, url_updated_at, url_deleted_at
`

type CreateUrlParams struct {
	RandomKey            string    `json:"random_key"`
	IosDeepLink          string    `json:"ios_deep_link"`
	IosFallbackUrl       string    `json:"ios_fallback_url"`
	AndroidDeepLink      string    `json:"android_deep_link"`
	AndroidFallbackUrl   string    `json:"android_fallback_url"`
	DefaultFallbackUrl   string    `json:"default_fallback_url"`
	HashedValueUrl       *string   `json:"hashed_value_url"`
	WebhookUrl           string    `json:"webhook_url"`
	OpengraphTitle       *string   `json:"opengraph_title"`
	OpengraphDescription string    `json:"opengraph_description"`
	OpengraphImage       string    `json:"opengraph_image"`
	IsActive             bool      `json:"is_active"`
	UserUuid             uuid.UUID `json:"user_uuid"`
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createUrl,
		arg.RandomKey,
		arg.IosDeepLink,
		arg.IosFallbackUrl,
		arg.AndroidDeepLink,
		arg.AndroidFallbackUrl,
		arg.DefaultFallbackUrl,
		arg.HashedValueUrl,
		arg.WebhookUrl,
		arg.OpengraphTitle,
		arg.OpengraphDescription,
		arg.OpengraphImage,
		arg.IsActive,
		arg.UserUuid,
	)
	var i Url
	err := row.Scan(
		&i.UrlID,
		&i.UserUuid,
		&i.RandomKey,
		&i.DefaultFallbackUrl,
		&i.HashedValueUrl,
		&i.IosDeepLink,
		&i.IosFallbackUrl,
		&i.AndroidDeepLink,
		&i.AndroidFallbackUrl,
		&i.WebhookUrl,
		&i.OpengraphTitle,
		&i.OpengraphDescription,
		&i.OpengraphImage,
		&i.IsActive,
		&i.UrlCreatedAt,
		&i.UrlUpdatedAt,
		&i.UrlDeletedAt,
	)
	return i, err
}

const findUrlByHashed = `-- name: FindUrlByHashed :one
SELECT url_id, user_uuid, random_key, default_fallback_url, hashed_value_url, ios_deep_link, ios_fallback_url, android_deep_link, android_fallback_url, webhook_url, opengraph_title, opengraph_description, opengraph_image, is_active, url_created_at, url_updated_at, url_deleted_at
FROM urls
WHERE hashed_value_url = $1::TEXT AND url_deleted_at IS NULL
LIMIT 1
`

func (q *Queries) FindUrlByHashed(ctx context.Context, hashedValueUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, findUrlByHashed, hashedValueUrl)
	var i Url
	err := row.Scan(
		&i.UrlID,
		&i.UserUuid,
		&i.RandomKey,
		&i.DefaultFallbackUrl,
		&i.HashedValueUrl,
		&i.IosDeepLink,
		&i.IosFallbackUrl,
		&i.AndroidDeepLink,
		&i.AndroidFallbackUrl,
		&i.WebhookUrl,
		&i.OpengraphTitle,
		&i.OpengraphDescription,
		&i.OpengraphImage,
		&i.IsActive,
		&i.UrlCreatedAt,
		&i.UrlUpdatedAt,
		&i.UrlDeletedAt,
	)
	return i, err
}
