// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const cleanSoftDelete = `-- name: CleanSoftDelete :one
DELETE FROM users
WHERE
    user_deleted_at IS NOT NULL AND user_uuid = $1::uuid
RETURNING user_id, user_uuid, user_email, user_password, user_role, user_status, user_created_at, user_updated_at, user_deleted_at
`

func (q *Queries) CleanSoftDelete(ctx context.Context, userUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, cleanSoftDelete, userUuid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserDeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    user_email,
    user_password,
    user_status,
    user_role
) VALUES(
    $1,$2,$3,$4
) RETURNING user_id, user_uuid, user_email, user_password, user_role, user_status, user_created_at, user_updated_at, user_deleted_at
`

type CreateUserParams struct {
	UserEmail    string `json:"user_email"`
	UserPassword string `json:"user_password"`
	UserStatus   int32  `json:"user_status"`
	UserRole     int32  `json:"user_role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserEmail,
		arg.UserPassword,
		arg.UserStatus,
		arg.UserRole,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserDeletedAt,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT user_id, user_uuid, user_email, user_password, user_role, user_status, user_created_at, user_updated_at, user_deleted_at
FROM users
WHERE
    user_uuid = $1::uuid
    AND user_deleted_at IS NULL
`

func (q *Queries) GetUserByUUID(ctx context.Context, userUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, userUuid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserDeletedAt,
	)
	return i, err
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET
    user_deleted_at = NULL
WHERE
    user_deleted_at IS NOT NULL AND user_uuid = $1::uuid
RETURNING user_id, user_uuid, user_email, user_password, user_role, user_status, user_created_at, user_updated_at, user_deleted_at
`

func (q *Queries) RestoreUser(ctx context.Context, userUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, userUuid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserDeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET
    user_deleted_at = now()
WHERE
    user_uuid = $1::uuid AND user_deleted_at IS NULL
RETURNING user_id, user_uuid, user_email, user_password, user_role, user_status, user_created_at, user_updated_at, user_deleted_at
`

func (q *Queries) SoftDeleteUser(ctx context.Context, userUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, userUuid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserDeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    user_password = COALESCE($1, user_password),
    user_status = COALESCE($2, user_status),
    user_role = COALESCE($3, user_role)
WHERE
    user_uuid = $4::uuid AND user_deleted_at IS NULL
RETURNING user_id, user_uuid, user_email, user_password, user_role, user_status, user_created_at, user_updated_at, user_deleted_at
`

type UpdateUserParams struct {
	UserPassword *string   `json:"user_password"`
	UserStatus   *int32    `json:"user_status"`
	UserRole     *int32    `json:"user_role"`
	UserUuid     uuid.UUID `json:"user_uuid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserPassword,
		arg.UserStatus,
		arg.UserRole,
		arg.UserUuid,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserDeletedAt,
	)
	return i, err
}
